Repository HSU-likelion13-BeArchive/Frontend, pull requests merged in 2025-05, with the labels that each got.

#3 MainGrid 컴포넌트
  moamoa/package-lock.json
  moamoa/package.json
  moamoa/src/assets/images/folder-empty.svg
  moamoa/src/assets/images/folder-full.svg
  moamoa/src/components/common/dialog/Dialog.scss
  moamoa/src/components/contents/maingrid/Grid.jsx
  moamoa/src/components/contents/maingrid/MainGrid.jsx
  moamoa/src/components/contents/maingrid/MainGrid.scss
  moamoa/src/components/contents/maingrid/folderitem/FolderItem.jsx
  moamoa/src/components/contents/maingrid/folderitem/FolderItem.scss
  moamoa/src/components/layout/folderlist/FolderList.jsx
  moamoa/src/components/layout/folderlist/FolderList.scss
  moamoa/src/components/layout/folderlist/FolderListItem.jsx
  moamoa/src/hooks/useEditableInput.js
  moamoa/src/styles/_variables.scss
Labels: Design

#4 Header 컴포넌트
  moamoa/src/assets/images/logo-text.svg
  moamoa/src/components/layout/header/Header.jsx
  moamoa/src/components/layout/header/Header.scss
  moamoa/src/components/layout/header/HomeButton.jsx
  moamoa/src/components/layout/header/Logo.jsx
Labels: Design

#6 Archive 컴포넌트
  moamoa/package-lock.json
  moamoa/src/assets/images/archive-icon1.svg
  moamoa/src/components/contents/archive/Archive.jsx
  moamoa/src/components/contents/archive/ArchiveCard.jsx
  moamoa/src/components/contents/archive/BrainstormButton.jsx
  moamoa/src/components/contents/archive/UploadButton.jsx
  moamoa/src/components/contents/archive/archive.scss
  moamoa/src/pages/archivePage/ArchivePage.jsx
Labels: Design

#7 Brainstorming 컴포넌트
  moamoa/src/App.jsx
  moamoa/src/assets/images/brainstorming-loading.svg
  moamoa/src/components/common/spinner/LoadingSpinner.jsx
  moamoa/src/components/common/spinner/LoadingSpinner.scss
  moamoa/src/components/contents/brainstorming/Brainstorming.jsx
  moamoa/src/components/contents/brainstorming/Brainstorming.scss
  moamoa/src/components/contents/brainstorming/ChatArea.jsx
  moamoa/src/components/contents/brainstorming/ReferenceInfo.jsx
  moamoa/src/data/dummyRefs.json
  moamoa/src/hooks/useRefData.js
  moamoa/src/pages/BrainstormingPage.jsx
  moamoa/src/pages/MainPage.jsx
  moamoa/src/pages/brainstormingPage/BrainstormingPage.jsx
Labels: Design

#9 LoginForm, SignupForm 컴포넌트
  moamoa/package-lock.json
  moamoa/package.json
  moamoa/src/App.jsx
  moamoa/src/assets/images/logo-sign.svg
  moamoa/src/components/common/account/Account.scss
  moamoa/src/components/common/account/AccountButton.jsx
  moamoa/src/components/common/account/AccountInput.jsx
  moamoa/src/components/login/LoginForm.jsx
  moamoa/src/components/sign/LoginForm.jsx
  moamoa/src/components/sign/SignForm.scss
  moamoa/src/components/sign/SignupForm.jsx
  moamoa/src/components/signup/SignupForm.jsx
  moamoa/src/hooks/useIdValidation.js
  moamoa/src/hooks/useLoginError.js
  moamoa/src/hooks/usePwValidation.js
  moamoa/src/pages/LoginPage.jsx
  moamoa/src/pages/SignupPage.jsx
  moamoa/src/pages/loginPage/LoginPage.jsx
  moamoa/src/pages/signupPage/SignupPage.jsx
  moamoa/src/styles/_mixins.scss
  moamoa/src/styles/_variables.scss
  moamoa/src/utils/validation.js
Labels: Design

#11 Archive 컴포넌트 기능
  moamoa/package-lock.json
  moamoa/package.json
  moamoa/src/assets/images/empty-archive.svg
  moamoa/src/components/contents/archive/Archive.jsx
  moamoa/src/components/contents/archive/ArchiveCard.jsx
  moamoa/src/components/contents/archive/EmptyBoard.jsx
  moamoa/src/components/contents/archive/UploadButton.jsx
  moamoa/src/components/contents/archive/UploadDialog.jsx
  moamoa/src/components/contents/archive/UploadDialog.scss
  moamoa/src/components/contents/archive/UploadDropzone.jsx
  moamoa/src/components/contents/archive/archive.scss
Labels: Design

#18 로그인, 회원가입 api 연동
  moamoa/src/App.jsx
  moamoa/src/api/user/checkIdApi.js
  moamoa/src/api/user/loginUserApi.js
  moamoa/src/api/user/signupUserApi.js
  moamoa/src/components/common/account/AccountButton.jsx
  moamoa/src/components/sign/LoginForm.jsx
  moamoa/src/components/sign/SignupForm.jsx
  moamoa/src/hooks/useIdValidation.js
  moamoa/src/pages/ArchivePage.jsx
  moamoa/src/pages/notfoundPage/NotFoundPage.scss
Labels: Feat

#24 폴더 수정 오류, FolderList와 MainGrid 동기화
  moamoa/src/App.jsx
  moamoa/src/ProtectedRoute.jsx
  moamoa/src/api/folder/setFolderOrderApi.js
  moamoa/src/components/contents/maingrid/MainGrid.jsx
  moamoa/src/components/layout/Layout.jsx
  moamoa/src/components/layout/folderlist/FolderList.jsx
  moamoa/src/components/layout/folderlist/FolderListItem.jsx
  moamoa/src/contexts/FolderContext.jsx
  moamoa/src/hooks/useFolderList.js
Labels: Feat, Fix

#25 AI 채팅, Wordcloud 시각화
  moamoa/src/api/brainstorming/getRecomIdApi.js
  moamoa/src/api/brainstorming/historyChatApi.js
  moamoa/src/api/brainstorming/sendChatApi.js
  moamoa/src/api/brainstorming/startChatApi.js
  moamoa/src/api/keywords/extractKeywordsApi.js
  moamoa/src/api/keywords/getKeywordsByFolderIdApi.js
  moamoa/src/assets/images/chat-bot.svg
  moamoa/src/components/contents/archive/Archive.jsx
  moamoa/src/components/contents/brainstorming/Brainstorming.jsx
  moamoa/src/components/contents/brainstorming/Brainstorming.scss
  moamoa/src/components/contents/brainstorming/ChatArea.jsx
  moamoa/src/components/contents/maingrid/MainGrid.jsx
  moamoa/src/components/contents/wordcloud/Wordcloud.jsx
  moamoa/src/components/layout/folderlist/FolderList.jsx
  moamoa/src/components/layout/folderlist/FolderList.scss
  moamoa/src/components/layout/folderlist/FolderListItem.jsx
  moamoa/src/contexts/FolderContext.jsx
  moamoa/src/hooks/useAutoScroll.js
  moamoa/src/hooks/useThinkingDots.js
  moamoa/src/pages/WordcloudPage.jsx
Labels: Feat

#26 🔧 : vite 위치 변경
  moamoa/package-lock.json
  moamoa/package.json
Labels: Fix
